### ISSUE TITLE
order of labeled nodes

### ISSUE THREAD

**Issue by pebbe** [andreasvc/tgrep2#2] opened 2019-10-17 17:11 UTC
This does not what I expect it to do:
```
$ tgrep2 -l -c test.t2c '* < ( noot < *=a ) < ( wim < ( * ~ =a ) )'
(aap (noot x)
     (mies y)
     (wim x)
     (zus z))
(fiets (noot v)
       (mies y)
       (wim x)
       (zus z))
```

The following gives the output I expected in the first case, but the expressions seems awkward. Is there a reason you must write it like this, or is this a bug?

```
$  tgrep2 -l -c test.t2c '* << ( *=a > noot ) < ( wim < (* ~ =a) )'
(aap (noot x)
     (mies y)
     (wim x)
     (zus z))
```

**Comment by andreasvc** [comment] 2019-10-17 18:37
I did not design/create TGrep2, I only maintain this fork.
Refer to the manual for details about the syntax:
http://tedlab.mit.edu/~dr/Tgrep2/tgrep2.pdf
I have to admit I find the query syntax confusing myself.
I believe the issue you are experiencing is explained on p. 12.
Use `-z` to show how the query is interpreted. When a copy of a named node is made, a `+` is added to the name and the query does not work as intended.
Here's another way to do your query:

    $ tgrep2 -z -l -c test.t2c '*=A < (wim < *=B ) : (=B ~ (* > (noot > =A)))'
    (*=A < (wim < (*=B ~ (* > (noot > =A)))));
    (aap (noot x) (mies y) (wim x) (zus z))

**Comment by andreasvc** [comment] 2019-10-24 18:28
Closing because this seems to work as intended (but feel free to re-open if you disagree).

**Closed as completed by andreasvc** 2019-10-24 18:28 UTC
